### ISSUE TITLE
The program does nothing and is unresponsive.

### ISSUE THREAD

**Issue by cryptoQKD** [smallcloudai/refact-intellij#10]
The program does nothing and is unresponsive.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Try plugin version 1.5. 1.4.9 had a lot of issues for me

**Comment by hazratisulton** [comment]
https://plugins.jetbrains.com/plugin/download?rel=true&updateId=599356 1.4.1 - not reproducible
