### ISSUE TITLE
where is login in pycharm Refact.ai plugin?

### ISSUE THREAD

**Issue by tincochan** [smallcloudai/refact-intellij#11]
![WX20230616-141459@2x](https://github.com/smallcloudai/refact-intellij/assets/34474781/67a847ee-f544-4782-a3c6-800fdedb4a50)

I install the plugin in pycharm and it shows on sidebar, but I cannot find where to log in and trigger any conversation.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
It should pop-up automatically in the lower right corner repeatedly...

Which version of PyCharm and Refact.ai are you using?

**Comment by olegklimov** [comment]
I think this is fixed in the latest JB version.

In the previous version you could find login in status bar, and settings. In the new version you also have it in the side panel.

**Comment by olegklimov** [comment]
Confirmed -- that's fixed. Reopen if any more problems!

**Comment by tincochan** [comment]
Thanks, I see your update notification and it's fixed. By the way, I confirm my pycharm is the latest version(2023.1.2 built on May, 17th, 2023)
