### ISSUE TITLE
Put ⚙️ cog button somewhere to access plugin settings easily

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-intellij#16]
Otherwise settings are hard to find.

**Comment by nikitakoselev** [comment]
Basically that is the information I would expect to see after clicking the "cog button". 
Settings -> Tools -> Refact.ai: 
![image](https://github.com/smallcloudai/refact-intellij/assets/6383738/0d334b77-bd43-47d7-940e-f03b6791ea3c)

**Comment by hazratisulton** [comment]
1.4.1 
![image](https://github.com/user-attachments/assets/6da63911-1c2f-497e-96e2-068aaab181be)
