### ISSUE TITLE
[UI]  Icon and tooltip text do not change when selecting files with different privacy level

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact-intellij#17]
Precondition: 
Two files, file0 with Privacy Rule Level 0 and file1 with Privacy Rule Level 1

Steps: 
1. Open file1 and check the Refact icon and tooltip text
3. Attempt to use autocompletion in file1
3. Open file0 and check the Refact icon and tooltip text
4. Attempt to use autocompletion in file0

Expected results: 
1. Icon and tooltip text for file1 should reflect that the privacy level is not zero and display Refact icon
2. Autocompletion should work
3. Icon and tooltip text for file1 should reflect that the privacy level is zero and display  "hand" icon
4. Autocompletion should not work

Actual result:
1. Icon and text are displayed for last selected Privacy Rule. This may or may not be correct depending on the last selected Privacy Rule.
2. Autocompletion is working
3. Icon and text are displayed for last selected Privacy Rule. This may or may not be correct depending on the last selected Privacy Rule.
4. Autocompletion is not working

[Screencast from 03-08-23 04:14:12.webm](https://github.com/smallcloudai/refact-intellij/assets/140423660/66bd3078-d868-4179-9400-a7762afd2615)

**Comment by olegklimov** [comment]
This sounds like completion is working or not working correctly, but the icon and the tooltip don't reflect the changes soon enough?

Thanks for reporting!

**Comment by hazratisulton** [comment]
> This sounds like completion is working or not working correctly, but the icon and the tooltip don't reflect the changes soon enough?
> 
> Thanks for reporting!

Yeah.

**Comment by hazratisulton** [comment]
1.1.53-fixes-9-b294d942 - NOT OK

**Comment by hazratisulton** [comment]
Fixed here https://plugins.jetbrains.com/plugin/20647-refact-ai/versions/stable/399313
