### ISSUE TITLE
[FIM] Adds odd number of spaces on Tab

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-intellij#20]
Code to reproduce:

```
def random_points_in_square(N: int = 100, square_size: float = 1):
    """
    Square is center [-square_size/2, square_size/2]
    """
    points = []
    for k in range(N):
```

![image](https://github.com/smallcloudai/refact-intellij/assets/18546213/8a07d7ec-4dfc-4bb4-a0c5-0339d69c8d04)

**Comment by olegklimov** [comment]
The reason: last token is 284 "\n   " (newline and three spaces, in StarCoder encoding)
Spaces after \n are added -- that's the odd spaces in question

**Comment by hazratisulton** [comment]
1.4.1 - not reproducible
