### ISSUE TITLE
Can't login with JetBrains plugin

### ISSUE THREAD

**Issue by 0dragosh** [smallcloudai/refact-intellij#26]
Upon clicking login I am redirected to `https://codify.smallcloud.ai/authentication?token=` -- where:

1. The SSL cert is wrong/expired
2. Even if I click through that I'm presented with a 404 from nginx

**Comment by olegklimov** [comment]
Thanks for reporting!

**Comment by olegklimov** [comment]
Fixed!
Huge thanks again for reporting!
