### ISSUE TITLE
[chat] Attaching invalid content

### ISSUE THREAD

**Issue by JegernOUTT** [smallcloudai/refact-intellij#28]
When I have an active console:
![Screenshot from 2023-09-02 01-57-27](https://github.com/smallcloudai/refact-intellij/assets/9404669/e4c3d8bd-c1e9-4211-a93b-a3502e7dbf71)

following buttons:
![Screenshot from 2023-09-02 01-57-55](https://github.com/smallcloudai/refact-intellij/assets/9404669/be2cd286-f2f3-4669-bc12-5e36296cc2ef)

are considering console as a context source.

So, instead of sending an opened file you're sending a console output

**Comment by hazratisulton** [comment]
1.1.53-fixes-9-b294d942 - OK

**Comment by hazratisulton** [comment]
Fixed here https://plugins.jetbrains.com/plugin/20647-refact-ai/versions/stable/399313
