### ISSUE TITLE
[completion] A problem with `\n` in the beginning of completion 

### ISSUE THREAD

**Issue by JegernOUTT** [smallcloudai/refact-intellij#29]
When a completion text starts with `\n`, the plugin just ignores this

An example:
```python
def quick_sort(arr):
```
You have to put the cursor to the end of the line and press `force completion` keys combination
You're going to receive such tokens:
```
-- 3389597 -- 20230902 02:08:02 MODEL   30.0ms "\n   "
-- 3389597 -- 20230902 02:08:02 MODEL   37.7ms " if"
-- 3389597 -- 20230902 02:08:02 MODEL   43.7ms " len"
-- 3389597 -- 20230902 02:08:02 MODEL   50.2ms "("
-- 3389597 -- 20230902 02:08:02 MODEL   56.3ms "arr"
-- 3389597 -- 20230902 02:08:02 MODEL   62.9ms ")"
-- 3389597 -- 20230902 02:08:02 MODEL   69.5ms " <="
-- 3389597 -- 20230902 02:08:02 MODEL   75.5ms " "
-- 3389597 -- 20230902 02:08:02 MODEL   81.9ms "1"
-- 3389597 -- 20230902 02:08:02 MODEL   88.8ms ":"
-- 3389597 -- 20230902 02:08:02 MODEL   94.8ms "\n       "
-- 3389597 -- 20230902 02:08:02 MODEL  101.4ms " return"
.....
```
But the plugin will never render them

**Comment by JegernOUTT** [comment]
It looks like the server responds with an extra head offset, implicitly ignoring `\n` 
Guess we should fix it server-side, maybe with migrating to a new scratchpad

**Comment by hazratisulton** [comment]
Checked plugin version 1.2.17. Now we get only one token (EOF) - nothing need to render.
