### ISSUE TITLE
Better monospace font in chat

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-intellij#3]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/18546213/225889094-f4aacdd2-a9cc-4cad-a407-350bdf60a84d.png">

Now looks like this: "%0.4f" doesn't even look like a different font. We want it more visible, highlighted in some way:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/18546213/225889930-7409e4ac-258c-423a-8054-750a14d4deb2.png">

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
It would be nice to be able to change the font as well, at least the size.

![image](https://github.com/smallcloudai/refact-intellij/assets/2598631/f6b40254-65d9-4cf3-bb3c-fe855322188f)

The code section is very large unless I have it fullscreen

**Comment by olegklimov** [comment]
Thanks for reporting!

**Comment by hazratisulton** [comment]
1.4.1 have new chat
