### ISSUE TITLE
ridiculous fill prompt at every new line prompt in the debugger console

### ISSUE THREAD

**Issue by Sigfried** [smallcloudai/refact-intellij#42]
It looks like this:

![image](https://github.com/smallcloudai/refact-intellij/assets/1586931/2db3fcb8-c955-4cde-b7cc-5bf6363dcbfc)

I get it over and over again and have to backspace to get rid of it before I can start typing whatever I'm trying to type.

**Comment by reymondzzzz** [comment]
Thanks for report. We fixed very similar bug in next version(hope it will be on this or next week).
