### ISSUE TITLE
add ability to have custom prompts and save them

### ISSUE THREAD

**Issue by BMomani** [smallcloudai/refact-intellij#57]
currently, you set some prompts for us, but most of the time we need refact to with custom instructions 
similar to https://cursor.sh/features 

ability to save those custom prompts and edit them would be great to fix/re-run them, as needed

with this small feature, you will make [Cursor IDE](https://cursor.sh) less attracting 

currently, I have both IDEs open  one for prompts and ai assistance and one for the IDE that I love,

please let me know how this sounds 🚀 or 👎. thanks

**Comment by reymondzzzz** [comment]
Hi! we are working on new chat and toolbox and we have some plans with this feature

**Comment by hazratisulton** [comment]
![image](https://github.com/user-attachments/assets/017430d9-ca79-4725-9f38-97f9bcea80fc)
1.4.1
