### ISSUE TITLE
"Add Privacy Rule" in context menu

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-intellij#6]
File context menu -> Add Privacy Rule: Turn Off
File context menu -> Add Privacy Rule: Level 1
File context menu -> Add Privacy Rule: Level 2

File context menu --> Privacy Rules

**Comment by hazratisulton** [comment]
Added here: https://github.com/smallcloudai/refact-intellij/commit/7a9adccc5d70f4fa0a2a01e2aeae436d9e4cc8a7
