### ISSUE TITLE
Bug with code completion

### ISSUE THREAD

**Issue by pixkk** [smallcloudai/refact-intellij#75]
Refact plugin version: 1.2.7-eap-c73abd0c

When i`m coding, it recommends autocompletion:
![image](https://github.com/smallcloudai/refact-intellij/assets/30828435/5d40636d-bdf9-410f-acdc-fafbf95684cd)

But when i click TAB button on keyboard, it writes more code, than he recommended before:
![image](https://github.com/smallcloudai/refact-intellij/assets/30828435/baa16c2b-9628-4e43-a70c-73a94231b024)

I don't know, it's bug of Refact or Plugin for Intellij. 

IntelliJ IDEA 2023.2.2 (Ultimate Edition)
Build #IU-232.9921.47, built on September 13, 2023
Runtime version: 17.0.8+7-b1000.22 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 16
Registry:
    ide.experimental.ui=true
Kotlin: 232-1.9.0-IJ9921.47

**Comment by reymondzzzz** [comment]
Thanks for report! Strange...first screenshot is connected to request and render delay. ex. You wrote but request was long and you got this completion. Second is similar to first, but 2 requests mixed. These are bugs. Fixes will be in the next release.

**Comment by reymondzzzz** [comment]
Hi again! Check pls plugin "full line code completion"
![Uploading image.png…]()
It could be not our completion.

**Comment by reymondzzzz** [comment]
![image](https://github.com/smallcloudai/refact-intellij/assets/15812493/c1f4aad9-bf24-4079-be3e-96a2b7e0812e)

**Comment by pixkk** [comment]
Up to this point, it was completely disabled (and even when it was enabled, I could not use it, since it apparently does not work with PHP).

Here IDEA probably has a limit on the length of the line (which is grayed out), which is why this “Bug” occurs.

**Comment by reymondzzzz** [comment]
We will release today-tomorrow new version(1.2.13). Try this one. I reworked completion a little bit, so hope it will fix this problem

**Comment by pixkk** [comment]
Maybe everything is ok (i dont see this bug at this moment)
