### ISSUE TITLE
Toolbox commands do not work.

### ISSUE THREAD

**Issue by Ryuukae** [smallcloudai/refact-intellij#82]
The toolbox has worked for me up until now but for some reason the feature has broken. The selected text still lights up with the moving colors as it should but nothing ever happens. No error message, just stays lit up forever until I deselect the test. This is in Intellij Idea (2023.2.3).

**Comment by valaises** [comment]
Hi, Ryuukae! Toolbox shan't work for some time until we're done with overhauling it. Thanks for reporting and patience!
