### ISSUE TITLE
[QUESTION] Supporting IDE versions

### ISSUE THREAD

**Issue by maldil** [smallcloudai/refact-intellij#9]
Hi,

Thanks for the great work. I tried installing the plugin for both PyCharm and IntelliJ, but I received an error message for both versions. Even after updating PyCharm to the latest version, I still get the same error. Could you please provide an idea of the supported versions of the IDEs required to use this plugin?

<img width="403" alt="Screen Shot 2023-04-06 at 11 18 56 AM" src="https://user-images.githubusercontent.com/20140049/230462459-eeb68446-d2a2-455b-9d58-96d33b4d0b76.png">

**Comment by olegklimov** [comment]
Thank you for reporting!

**Comment by reymondzzzz** [comment]
Hi! 

What PyCharm version do you have? We upgraded minimal version of IDE with last release.
The minimal version of PyCharm is 2022.2.1.

**Comment by maldil** [comment]
Thanks. It works now.
